### ISSUE TITLE
Chat #1

### ISSUE THREAD

**Issue by nnian** [qwertycoin-org/qwertycoin-gui#15]
Hi @speqtr i know that is not your case, but maybe you can help @exploshot 
He had used your Automate Deploy Script (qwertycoin-zero) to install it here, within the GUI.

But theres are problem with the Language files:

These are the correct Translations
https://github.com/qwertycoin-org/qwertycoin-gui/tree/master/src/languages

But the deployed versions contains random .qm Files which in fact cause the GUI to not work properly with the translations. Only the Default English Version is available. Do you have an idea to solve this problem?
Thanks =)

**Comment by speqtr** [comment]
Hi @nnian and @exploshot 🙂
Does it happen on a single platform (Linux, macOS, Windows)? Or on all of them?

**Comment by nnian** [comment]
Mh, a good question i've tested it on Windows there are no correct language files in the package. @exploshot did you tried it on all platforms?

**Comment by exploshot** [comment]
In the past we added the *.qm files manually to the translation folder. So i think its on every platform.
In the fork repo I've tried several things but nothing with a solution.
 
https://github.com/exploshot/fork_qwertycoin-gui

My next problem is, that the Zero and GUI don't have qt added for shipping.
e.g. if  i want install the zero or GUI deb on Ubuntu, i've to install qt only for this wallet.
Is there a way to include the files?

Next is that the deb don't have a symlink after installing, e.g. if i press the home button in Ubuntu and type in Qwertycoin i'll only find the .deb

**Comment by speqtr** [comment]
> My next problem is, that the Zero and GUI don't have qt added for shipping.
e.g. if i want install the zero or GUI deb on Ubuntu, i've to install qt only for this wallet.
Is there a way to include the files?

Qt5 libraries should be present in `deb` and `rpm` packages. Could you please check it by running `dpkg -c qwertycoin-zero-....deb`?

**Comment by speqtr** [comment]
> Next is that the deb don't have a symlink after installing, e.g. if i press the home button in Ubuntu and type in Qwertycoin i'll only find the .deb

This one I'll fix.

**Comment by exploshot** [comment]
> > My next problem is, that the Zero and GUI don't have qt added for shipping.
> > e.g. if i want install the zero or GUI deb on Ubuntu, i've to install qt only for this wallet.
> > Is there a way to include the files?
> 
> Qt5 libraries should be present in `deb` and `rpm` packages. Could you please check it by running `dpkg -c qwertycoin-zero-....deb`?

true, the zero contains the qt libs but not the gui, thats interesting, so my fault

![2019-08-08 19_39_36-Ubuntu 18 04 64-bit - VMware Workstation 15 Player (Non-commercial use only)](https://user-images.githubusercontent.com/9617859/62724903-4b7b6100-ba14-11e9-9bfc-0079e99a2b30.png)

**Comment by speqtr** [comment]
Most likely it's just a small typo in deployment script.
